import os

import pandas as pd
from google import genai
from google.genai import types

path_daily_data = '../data/daily/'
path_validated_data = '../data/daily_validati/'

# Config
API_KEY = os.environ["GEMINI_API_KEY"]
MODEL_ID = "gemini-2.5-flash"

# Create client
client = genai.Client(api_key=API_KEY)

# =========================
# GEMINI API CLIENT
# =========================
# Questo modulo contiene le funzioni per interfacciarsi con l'API Gemini,
# gestire le richieste, le risposte e la logica di autenticazione.
# Ogni funzione è commentata per spiegare il suo ruolo.


def load_file(date: str):
    """Carica i dati giornalieri da un file JSON.

    Args:
        date (str): La data nel formato YYYY-MM-DD.

    Returns:
        DataFrame: Un DataFrame pandas contenente i dati del file.
    """
    return pd.read_json(path_daily_data + date + '.json')


def get_value_pollutant(location: str, date: str, time: int, pollutant: str) -> float:
    """
    Retrieves the concentration value of a pollutant for a specific monitoring station,
    date, and hour.

    Args:
        location (str): Exact name of the monitoring station.
        date (str): Date in the format YYYY-MM-DD.
        time (int): Hour of the day (0–23).
        pollutant (str): Pollutant name (e.g., NO2, PM10, PM2,5, O3).

    Returns:
        float: Pollutant concentration value in µg/m³.
    """
    df = load_file(date)
    return df[
        (df["date"].dt.strftime("%Y-%m-%d") == date) &
        (df["date"].dt.hour == time) &
        (df["station_name"] == location) &
        (df["pollutant"] == pollutant)
    ].iloc()[0]["value"]


def get_station_name() -> list[str]:
    """
    Returns the list of available monitoring station names.

    Returns:
        list[str]: List of station names.
    """
    df = pd.read_json("../data/station_coords.json")
    return df.columns.tolist()


def get_pollutant_name():
    """
    Returns the list of monitored pollutants.

    Returns:
        list: List of pollutant names.
    """
    return ["CO", "NO2", "PM10", "PM2,5", "O3"]


def get_pollutant_description(pollutant: str) -> str:
    """
    Restituisce una breve descrizione dell'inquinante richiesto.

    Args:
        pollutant (str): Nome dell'inquinante.

    Returns:
        str: Descrizione dell'inquinante.
    """
    descriptions = {
        "CO": "Il monossido di carbonio (CO) è un gas incolore e inodore prodotto dalla combustione incompleta di combustibili fossili. Può essere pericoloso per la salute, specialmente in ambienti chiusi.",
        "NO2": "Il biossido di azoto (NO2) è un gas irritante prodotto principalmente dai veicoli e dagli impianti industriali. Può causare problemi respiratori e contribuisce alla formazione di smog.",
        "PM10": "Il particolato PM10 è costituito da particelle sospese con diametro inferiore a 10 micrometri. Può penetrare nelle vie respiratorie e causare problemi di salute.",
        "PM2,5": "Il particolato PM2,5 è formato da particelle molto fini (diametro inferiore a 2,5 micrometri) che possono raggiungere i polmoni profondi e il sistema circolatorio.",
        "O3": "L'ozono (O3) a livello del suolo è un inquinante secondario che si forma per reazione chimica tra altri inquinanti in presenza di luce solare. Può causare irritazione agli occhi e alle vie respiratorie."
    }
    return descriptions.get(pollutant, "Descrizione non disponibile per questo inquinante.")


def get_aqi_category(pollutant: str, value: float) -> str:
    pass

# Tool's list for chatbot
function_tools = [
    get_value_pollutant,
    get_station_name,
    get_pollutant_name,
    get_pollutant_description,
    #get_aqi_category
]

def send_request(request_user):
    """
    Sends a user request to Gemini, executes any requested tool calls,
    and returns the final natural-language response.

    Args:
        request_user (str): User request in natural language.

    Returns:
        str: Final response generated by the model.
    """
    response = client.models.generate_content(
        model=MODEL_ID,
        contents=request_user,
        config=types.GenerateContentConfig(
            tools=function_tools,
            system_instruction="""
            You are an air quality assistant.
            
            When the user asks for air quality:
                1.   First, call the function get_station_name to retrieve the name of the station closest to the requested location.
                2.   Then call the function to retrieve the pollutant value using that station.
                3.   Then call the function to classify the AQI category.
                4.   Provide a clear final answer including: station name, pollutant value, air quality category

            When the user asks for a description of a pollutant:
                1.   Call the function get_pollutant_description with the requested pollutant.
                2.   Provide the returned description in your answer.
            
            Always use the available tools when possible and follow this order strictly.
            """
        )
    )
    return response.text
